version: 2.1

aliases:
  - &auth
    username: $DOCKER_USER
    password: $DOCKER_PASS

  - &deploy-branches
    - prodexa

jobs:
  init:
    docker:
      - image: docker.artifacts.dev.prodexa.com/minsk-core-machineuser-env:2
        auth: *auth
    steps:
      - run:
          name: Inject secrets from vault to CircleCI project's environment
          command: circle_ci_add_env.sh
  build:
    docker:
      - image: node:21-slim
    working_directory: ~/build
    steps:
      - checkout
      - run:
          name: Build
          command: |
            set -eo pipefail
            npm install
            npm run build
  build_deploy:
    docker:
      - image: node:21-slim
    working_directory: ~/build
    steps:
      - checkout
      - run:
          name: Build, tar, publish
          command: |
            set -eo pipefail
            npm install
            npm run build
            npm run copy
            npm run package
            apt-get update && apt-get install --no-install-recommends -y bash ca-certificates openssh-client curl unzip
            curl -fsSLk -o /tmp/vault.zip https://releases.hashicorp.com/vault/1.3.2/vault_1.3.2_linux_amd64.zip \
            && unzip /tmp/vault.zip -d /usr/local/bin/ \
            && rm -f /tmp/vault.zip
            export JFROG_PASSWD=$( vault kv get -field=value machineuser/JFROG_PASSWD )
            export APP_VERSION=$( npm pkg get version | tr -d '"' )
            export APP_FILE=`echo ./prod/${CIRCLE_PROJECT_REPONAME}-${APP_VERSION}.tar.gz`
            echo "[INFO] APP_FILE:${APP_FILE}"
            export ARTIFACT_MD5_CHECKSUM=$(md5sum ${APP_FILE} | awk '{print $1}')
            export ARTIFACT_SHA1_CHECKSUM=$(shasum -a 1 ${APP_FILE} | awk '{ print $1 }')
            export ARTIFACT_SHA256_CHECKSUM=$(shasum -a 256 ${APP_FILE} | awk '{ print $1 }')
            echo "[INFO] Uploading pxc-storefront to JFrog maven-deploy/com/prodexa/${CIRCLE_PROJECT_REPONAME}/${APP_VERSION}/${CIRCLE_PROJECT_REPONAME}-${APP_VERSION}.tar.gz"
            echo "[INFO] MD5:${ARTIFACT_MD5_CHECKSUM}"
            echo "[INFO] SHA1:${ARTIFACT_SHA1_CHECKSUM}"
            echo "[INFO] SHA256:${ARTIFACT_SHA256_CHECKSUM}"
            curl -H 'X-JFrog-Art-Api:'"${JFROG_PASSWD}"'' \
            -H "X-Checksum-MD5:${ARTIFACT_MD5_CHECKSUM}" \
            -H "X-Checksum-Sha1:${ARTIFACT_SHA1_CHECKSUM}" \
            -H "X-Checksum-Sha256:${ARTIFACT_SHA256_CHECKSUM}" \
            -X PUT "https://artifacts.dev.prodexa.com/artifactory/maven-deploy/com/prodexa/${CIRCLE_PROJECT_REPONAME}/${APP_VERSION}/${CIRCLE_PROJECT_REPONAME}-${APP_VERSION}.tar.gz" \
            -T ${APP_FILE}
workflows:
  version: 2
  build-and-publish:
    jobs:
      - init:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - init
          filters:
            branches:
              ignore: *deploy-branches
      - build_deploy:
          requires:
            - init
          filters:
            tags:
              only: /.*/
            branches:
              only: *deploy-branches
